# Generated by Django 4.2 on 2025-08-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reszier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orignal_image', models.ImageField(upload_to='images/')),
                ('thumbnail_small', models.ImageField(upload_to='images/thumbnails')),
                ('thumbnail_medium', models.ImageField(upload_to='images/thumbnails')),
                ('thumbnail_large', models.ImageField(upload_to='images/thumbnails')),
            ],
        ),
    ]
