# Generated by Django 4.2 on 2025-08-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reszier', '0002_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='thumbnail_large',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnail'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='thumbnail_medium',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnail'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='thumbnail_small',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnail'),
        ),
    ]
