# Generated by Django 4.2 on 2025-08-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reszier', '0003_alter_imagemodel_thumbnail_large_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stdudent',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='imagemodel',
            old_name='orignal_image',
            new_name='original_image',
        ),
    ]
