# Generated by Django 4.2 on 2025-08-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reszier', '0004_rename_stdudent_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
